import Head from 'next/head';
import React, { FC, ReactNode } from 'react';
import styles from './LayoutGeneral.module.css';
import { Navbar } from '../ui';
interface _props {
	children: ReactNode;
}
export const LayoutGeneral: FC<_props> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Rick & Morty App</title>
				<meta name='description' content='Generated by Rick & Morty App' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className={styles.body}>{children}</main>
		</>
	);
};
